CREATE TABLE users (
    users_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username text NOT NULL,
    password text NOT NULL,
    admin INTEGER NOT NULL,
    date_created TIMESTAMP NOT NULL DEFAULT now() 
);